2019-08-18 18:27:45,398 INFO: Microblog startup [in /Users/Ming/PycharmProjects/flask/microblog/app/__init__.py:52]
2019-08-18 18:28:34,813 ERROR: Exception on /index [POST] [in /Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/routes.py", line 44, in index
    db.session.commit()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
    self.session.dispatch.after_commit(self.session)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/models.py", line 104, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/search.py", line 5, in add_to_index
    if not current_app.elasticsearch:
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
2019-08-18 18:28:44,147 ERROR: Exception on /index [POST] [in /Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/routes.py", line 44, in index
    db.session.commit()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
    self.session.dispatch.after_commit(self.session)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/models.py", line 104, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/search.py", line 5, in add_to_index
    if not current_app.elasticsearch:
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
2019-08-18 18:36:21,576 ERROR: Exception on / [POST] [in /Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/routes.py", line 44, in index
    db.session.commit()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/orm/session.py", line 501, in commit
    self.session.dispatch.after_commit(self.session)
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/sqlalchemy/event/attr.py", line 259, in __call__
    fn(*args, **kw)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/models.py", line 104, in after_commit
    add_to_index(obj.__tablename__, obj)
  File "/Users/Ming/PycharmProjects/flask/microblog/app/search.py", line 5, in add_to_index
    if not current_app.elasticsearch:
  File "/Users/Ming/PycharmProjects/flask/venv/lib/python3.7/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'Flask' object has no attribute 'elasticsearch'
2019-08-18 18:41:27,821 INFO: Microblog startup [in /Users/Ming/PycharmProjects/flask/microblog/app/__init__.py:52]
2019-08-18 18:46:35,574 INFO: Microblog startup [in /Users/Ming/PycharmProjects/flask/microblog/app/__init__.py:52]
2019-08-18 18:49:06,843 INFO: Microblog startup [in /Users/Ming/PycharmProjects/flask/microblog/app/__init__.py:52]
